### ISSUE TITLE
No unicode support

### ISSUE THREAD

**Issue by scottsievert** [aaren/notedown#16]
If I nbconvert on a markdown file that contains unicode, I obtain the following error:

```python
Traceback (most recent call last):
  File "/Users/scott/anaconda/bin/notedown", line 11, in <module>
    sys.exit(cli())
  File "/Users/scott/anaconda/lib/python2.7/site-packages/notedown/main.py", line 261, in cli
    writer.write(notebook, op)
  File "/Users/scott/anaconda/lib/python2.7/site-packages/IPython/nbformat/__init__.py", line 161, in write
    fp.write(s)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe8' in position 95: ordinal not in range(128)
```

I believe this is a simple fix (after you find the right place).

**Comment by aaren** [comment]
I'm not confident that notedown supports unicode but I can't reproduce your error.

Can you provide a minimal example that produces the error you are getting?

**Comment by scottsievert** [comment]
My minimal file:
```markdown
<!--test.md-->
®åéøß
```

Running `notedown test.md` I get

```shell
> notedown test.md
{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "test.md\n",
    "®åéøß"
   ]
  }
 ],
 "metadata": {},
 "nbformat": 4,
 "nbformat_minor": 0
}
```

Running `notedown test.md -o test.ipynb` or `notedown test.md > test.ipynb` I get the following error:

```shell
Traceback (most recent call last):
  File "/Users/scott/anaconda/bin/notedown", line 11, in <module>
    sys.exit(cli())
  File "/Users/scott/anaconda/lib/python2.7/site-packages/notedown/main.py", line 261, in cli
    writer.write(notebook, op)
  File "/Users/scott/anaconda/lib/python2.7/site-packages/IPython/nbformat/__init__.py", line 161, in write
    fp.write(s)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 85-89: ordinal not in range(128)
```
