### ISSUE TITLE
notedown doesn't work with Jupter Notebook 5.1.0

### ISSUE THREAD

**Issue by adonese** [aaren/notedown#60]
Whenever I run notedown it returns with this error
```shell
$ notedown 
Traceback (most recent call last):
  File "/home/adonese/anaconda3/bin/notedown", line 7, in <module>
    from notedown.main import app
  File "/home/adonese/anaconda3/lib/python3.5/site-packages/notedown/__init__.py", line 8, in <module>
    from .contentsmanager import NotedownContentsManager
  File "/home/adonese/anaconda3/lib/python3.5/site-packages/notedown/contentsmanager.py", line 8, in <module>
    from notebook.services.contents.filemanager import FileContentsManager
  File "/home/adonese/anaconda3/lib/python3.5/site-packages/notebook/services/contents/filemanager.py", line 21, in <module>
    from .manager import ContentsManager
  File "/home/adonese/anaconda3/lib/python3.5/site-packages/notebook/services/contents/manager.py", line 37, in <module>
    class ContentsManager(LoggingConfigurable):
  File "/home/adonese/anaconda3/lib/python3.5/site-packages/notebook/services/contents/manager.py", line 69, in ContentsManager
    untitled_notebook = Unicode(_("Untitled"), config=True,
NameError: name '_' is not defined
```
The same applied when I try to import it from python shell.

**Comment by undavide** [comment]
Same error here, even if with a slightly different stack trace:

```
(PYTHON3)  🦊  notedown
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/bin/notedown", line 7, in <module>
    from notedown.main import app
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/notedown/__init__.py", line 8, in <module>
    from .contentsmanager import NotedownContentsManager
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/notedown/contentsmanager.py", line 8, in <module>
    from notebook.services.contents.filemanager import FileContentsManager
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/notebook/services/contents/filemanager.py", line 21, in <module>
    from .manager import ContentsManager
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/notebook/services/contents/manager.py", line 37, in <module>
    class ContentsManager(LoggingConfigurable):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/notebook/services/contents/manager.py", line 69, in ContentsManager
    untitled_notebook = Unicode(_("Untitled"), config=True,
NameError: name '_' is not defined
```

Thanks!

**Comment by pca2** [comment]
Ditto on 2.7:

```
Traceback (most recent call last):
  File "/usr/local/bin/notedown", line 7, in <module>
    from notedown.main import app
  File "/usr/local/lib/python2.7/site-packages/notedown/__init__.py", line 8, in <module>
    from .contentsmanager import NotedownContentsManager
  File "/usr/local/lib/python2.7/site-packages/notedown/contentsmanager.py", line 8, in <module>
    from notebook.services.contents.filemanager import FileContentsManager
  File "/usr/local/lib/python2.7/site-packages/notebook/services/contents/filemanager.py", line 21, in <module>
    from .manager import ContentsManager
  File "/usr/local/lib/python2.7/site-packages/notebook/services/contents/manager.py", line 37, in <module>
    class ContentsManager(LoggingConfigurable):
  File "/usr/local/lib/python2.7/site-packages/notebook/services/contents/manager.py", line 69, in ContentsManager
    untitled_notebook = Unicode(_("Untitled"), config=True,
NameError: name '_' is not defined
```

**Comment by grst** [comment]
adding 
```python
import notebook.transutils
```
on top of each file which imports from `manager` should fix the issue. 

See https://github.com/jupyter/notebook/issues/2798

**Comment by holgerbrandl** [comment]
Same error here!

**Comment by aaren** [comment]
latest master should fix this, but note that this is still using the v4 notebook format.
