### ISSUE TITLE
pip install failed (format missing)

### ISSUE THREAD

**Issue by Benature** [aaren/notedown#90]
I run

```shell
pip install notedown -i https://pypi.org/simple
```

but get

```shell
Collecting notedown
  Downloading notedown-1.5.1-py3-none-any.whl (19 kB)
Requirement already satisfied: six in ./miniconda3/lib/python3.7/site-packages (from notedown) (1.14.0)
Requirement already satisfied: nbconvert in ./miniconda3/lib/python3.7/site-packages (from notedown) (5.6.1)
Collecting pandoc-attributes
  Using cached pandoc-attributes-0.1.7.tar.gz (2.6 kB)
    ERROR: Command errored out with exit status 1:
     command: /Users/benature/miniconda3/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/fs/8qzjz7zj3gl6ckcfdg5rgwp40000gn/T/pip-install-gnh2s95m/pandoc-attributes/setup.py'"'"'; __file__='"'"'/private/var/folders/fs/8qzjz7zj3gl6ckcfdg5rgwp40000gn/T/pip-install-gnh2s95m/pandoc-attributes/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/fs/8qzjz7zj3gl6ckcfdg5rgwp40000gn/T/pip-pip-egg-info-jxk3k2y3
         cwd: /private/var/folders/fs/8qzjz7zj3gl6ckcfdg5rgwp40000gn/T/pip-install-gnh2s95m/pandoc-attributes/
    Complete output (9 lines):
    /private/var/folders/fs/8qzjz7zj3gl6ckcfdg5rgwp40000gn/T/pip-install-gnh2s95m/pandoc-attributes/setup.py:5: DeprecationWarning: Due to possible ambiguity, 'convert()' is deprecated. Use 'convert_file()'  or 'convert_text()'.
      long_description = pypandoc.convert('README.md', 'rst')
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/fs/8qzjz7zj3gl6ckcfdg5rgwp40000gn/T/pip-install-gnh2s95m/pandoc-attributes/setup.py", line 5, in <module>
        long_description = pypandoc.convert('README.md', 'rst')
      File "/Users/benature/miniconda3/lib/python3.7/site-packages/pypandoc/__init__.py", line 66, in convert
        raise RuntimeError("Format missing, but need one (identified source as text as no "
    RuntimeError: Format missing, but need one (identified source as text as no file with that name was found).
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

It seems it's caused by the deprecated pandoc function `convert()`

---

os: macOS 10.15.6
pandoc:

```
pandoc 2.2.3.2
Compiled with pandoc-types 1.17.5.1, texmath 0.11.0.1, skylighting 0.7.2
```

**Comment by Benature** [comment]
solved with <https://github.com/aaren/pandoc-attributes/issues/1>
